name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
          apps: sbt
      - name: Run tests
        run: sbt +test